CREATE DATABASE IF NOT EXISTS kasutajad;
USE kasutajad;

CREATE TABLE IF NOT EXISTS visitors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_returning TINYINT(1) DEFAULT 0,
    visit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);